// Your training plan data, generated by the Python script
const trainingPlan = [
    {
        "week": "Week 1",
        "dateRange": [
            "December 02, 2024",
            "December 03, 2024",
            "December 04, 2024",
            "December 05, 2024",
            "December 06, 2024",
            "December 07, 2024",
            "December 08, 2024"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "December 02, 2024",
                "trainingPhase": "Base Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "December 03, 2024",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3",
                "duration": "30-40 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "December 04, 2024",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "December 05, 2024",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "December 06, 2024",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "December 07, 2024",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "4",
                "duration": "~ 45 minutes",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "December 08, 2024",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "18"
            }
        ]
    },
    {
        "week": "Week 2",
        "dateRange": [
            "December 09, 2024",
            "December 10, 2024",
            "December 11, 2024",
            "December 12, 2024",
            "December 13, 2024",
            "December 14, 2024",
            "December 15, 2024"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "December 09, 2024",
                "trainingPhase": "Base Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "December 10, 2024",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3",
                "duration": "30-40 mins",
                "pace": "11-12 min/mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "December 11, 2024",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "December 12, 2024",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 min/mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "December 13, 2024",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "December 14, 2024",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "5",
                "duration": "~ 55-60 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "December 15, 2024",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "19"
            }
        ]
    },
    {
        "week": "Week 3",
        "dateRange": [
            "December 16, 2024",
            "December 17, 2024",
            "December 18, 2024",
            "December 19, 2024",
            "December 20, 2024",
            "December 21, 2024",
            "December 22, 2024"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "December 16, 2024",
                "trainingPhase": "Base Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "December 17, 2024",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3",
                "duration": "30-40 mins",
                "pace": "11-12 min/mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "December 18, 2024",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "December 19, 2024",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 min/mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "December 20, 2024",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "December 21, 2024",
                "trainingPhase": "Base Building",
                "workoutType": "Hawaii, fit in a few easy runs",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "December 22, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "14"
            }
        ]
    },
    {
        "week": "Week 4",
        "dateRange": [
            "December 23, 2024",
            "December 24, 2024",
            "December 25, 2024",
            "December 26, 2024",
            "December 27, 2024",
            "December 28, 2024",
            "December 29, 2024"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "December 23, 2024",
                "trainingPhase": "Base Building",
                "workoutType": "",
                "miles": "3",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "December 24, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "December 25, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "December 26, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "3",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "December 27, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "December 28, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "December 29, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "3",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "9"
            }
        ]
    },
    {
        "week": "Week 5",
        "dateRange": [
            "December 30, 2024",
            "December 31, 2024",
            "January 01, 2025",
            "January 02, 2025",
            "January 03, 2025",
            "January 04, 2025",
            "January 05, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "December 30, 2024",
                "trainingPhase": "Base Building",
                "workoutType": "",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "December 31, 2024",
                "trainingPhase": "",
                "workoutType": "",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "January 01, 2025",
                "trainingPhase": "Base Building",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "January 02, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 min/mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "January 03, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "January 04, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "5",
                "duration": "~ 55-60 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "January 05, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "11"
            }
        ]
    },
    {
        "week": "Week 6",
        "dateRange": [
            "January 06, 2025",
            "January 07, 2025",
            "January 08, 2025",
            "January 09, 2025",
            "January 10, 2025",
            "January 11, 2025",
            "January 12, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "January 06, 2025",
                "trainingPhase": "Base Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "January 07, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3",
                "duration": "30-40 mins",
                "pace": "11-12 min/mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "January 08, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "January 09, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 min/mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "January 10, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "January 11, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "6",
                "duration": "~ 1hr 10 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "January 12, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "20"
            }
        ]
    },
    {
        "week": "Week 7",
        "dateRange": [
            "January 13, 2025",
            "January 14, 2025",
            "January 15, 2025",
            "January 16, 2025",
            "January 17, 2025",
            "January 18, 2025",
            "January 19, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "January 13, 2025",
                "trainingPhase": "Base Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "January 14, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "January 15, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "January 16, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "January 17, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "January 18, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "7",
                "duration": "~ 1hr 20 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "January 19, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "21"
            }
        ]
    },
    {
        "week": "Week 8",
        "dateRange": [
            "January 20, 2025",
            "January 21, 2025",
            "January 22, 2025",
            "January 23, 2025",
            "January 24, 2025",
            "January 25, 2025",
            "January 26, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "January 20, 2025",
                "trainingPhase": "Base Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "January 21, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "January 22, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "January 23, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "January 24, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "January 25, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "8",
                "duration": "~ 1.5 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "January 26, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "22"
            }
        ]
    },
    {
        "week": "Week 9",
        "dateRange": [
            "January 27, 2025",
            "January 28, 2025",
            "January 29, 2025",
            "January 30, 2025",
            "January 31, 2025",
            "February 01, 2025",
            "February 02, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "January 27, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "January 28, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "January 29, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "January 30, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 2.4",
                "duration": "20-25 mins",
                "pace": "~ 9:20 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "January 31, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "February 01, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "9",
                "duration": "~ 1 hr 45 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "February 02, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "22.4"
            }
        ]
    },
    {
        "week": "Week 10",
        "dateRange": [
            "February 03, 2025",
            "February 04, 2025",
            "February 05, 2025",
            "February 06, 2025",
            "February 07, 2025",
            "February 08, 2025",
            "February 09, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "February 03, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "February 04, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "February 05, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "February 06, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 2.5",
                "duration": "20-25 mins",
                "pace": "~ 9:15 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "February 07, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "February 08, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "10",
                "duration": "~ 2 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "February 09, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "23.5"
            }
        ]
    },
    {
        "week": "Week 11",
        "dateRange": [
            "February 10, 2025",
            "February 11, 2025",
            "February 12, 2025",
            "February 13, 2025",
            "February 14, 2025",
            "February 15, 2025",
            "February 16, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "February 10, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "February 11, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "February 12, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "February 13, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 2.75",
                "duration": "25-30 mins",
                "pace": "~ 9:15 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "February 14, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "February 15, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "8",
                "duration": "~ 1.5 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "February 16, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "21.75"
            }
        ]
    },
    {
        "week": "Week 12",
        "dateRange": [
            "February 17, 2025",
            "February 18, 2025",
            "February 19, 2025",
            "February 20, 2025",
            "February 21, 2025",
            "February 22, 2025",
            "February 23, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "February 17, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "February 18, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "February 19, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "February 20, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 3",
                "duration": "25-30 mins",
                "pace": "~ 9:10 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "February 21, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "February 22, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "10",
                "duration": "~ 2 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "February 23, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "24"
            }
        ]
    },
    {
        "week": "Week 13",
        "dateRange": [
            "February 24, 2025",
            "February 25, 2025",
            "February 26, 2025",
            "February 27, 2025",
            "February 28, 2025",
            "March 01, 2025",
            "March 02, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "February 24, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "February 25, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "February 26, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "February 27, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 3.4",
                "duration": "30-35 mins",
                "pace": "~ 9:10 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "February 28, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "March 01, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "11",
                "duration": "~ 2 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "March 02, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "25.4"
            }
        ]
    },
    {
        "week": "Week 14",
        "dateRange": [
            "March 03, 2025",
            "March 04, 2025",
            "March 05, 2025",
            "March 06, 2025",
            "March 07, 2025",
            "March 08, 2025",
            "March 09, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "March 03, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "March 04, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "March 05, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "March 06, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 3.6",
                "duration": "30-35 mins",
                "pace": "~ 9:05 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "March 07, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "March 08, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "8",
                "duration": "~ 1.5 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "March 09, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "22.6"
            }
        ]
    },
    {
        "week": "Week 15",
        "dateRange": [
            "March 10, 2025",
            "March 11, 2025",
            "March 12, 2025",
            "March 13, 2025",
            "March 14, 2025",
            "March 15, 2025",
            "March 16, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "March 10, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "March 11, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "March 12, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "March 13, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 4",
                "duration": "35-40 mins",
                "pace": "~ 9:05 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "March 14, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "March 15, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "11",
                "duration": "~ 2 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "March 16, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "26"
            }
        ]
    },
    {
        "week": "Week 16",
        "dateRange": [
            "March 17, 2025",
            "March 18, 2025",
            "March 19, 2025",
            "March 20, 2025",
            "March 21, 2025",
            "March 22, 2025",
            "March 23, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "March 17, 2025",
                "trainingPhase": "Endurance Building",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "March 18, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "March 19, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "March 20, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 4.3",
                "duration": "35-40 mins",
                "pace": "~ 9:00 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "March 21, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "March 22, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "12",
                "duration": "~ 2 hrs 20 mins",
                "pace": "11-12/mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "March 23, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "27.3"
            }
        ]
    },
    {
        "week": "Week 17",
        "dateRange": [
            "March 24, 2025",
            "March 25, 2025",
            "March 26, 2025",
            "March 27, 2025",
            "March 28, 2025",
            "March 29, 2025",
            "March 30, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "March 24, 2025",
                "trainingPhase": "Speed & Strength",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "March 25, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "March 26, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "March 27, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 4.3",
                "duration": "40 mins",
                "pace": "~ 9:00 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "March 28, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "March 29, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "10",
                "duration": "~ 2 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "March 30, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "25.3"
            }
        ]
    },
    {
        "week": "Week 18",
        "dateRange": [
            "March 31, 2025",
            "April 01, 2025",
            "April 02, 2025",
            "April 03, 2025",
            "April 04, 2025",
            "April 05, 2025",
            "April 06, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "March 31, 2025",
                "trainingPhase": "Speed & Strength",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "April 01, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "April 02, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "April 03, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 4.4",
                "duration": "40 mins",
                "pace": "~ 8:55 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "April 04, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "April 05, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "12",
                "duration": "~ 2 hrs 20 mins",
                "pace": "11-12/mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "April 06, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "27.4"
            }
        ]
    },
    {
        "week": "Week 19",
        "dateRange": [
            "April 07, 2025",
            "April 08, 2025",
            "April 09, 2025",
            "April 10, 2025",
            "April 11, 2025",
            "April 12, 2025",
            "April 13, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "April 07, 2025",
                "trainingPhase": "Speed & Strength",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "April 08, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "April 09, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "April 10, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 4.4",
                "duration": "40 mins",
                "pace": "~ 8:55 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "April 11, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "April 12, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "13",
                "duration": "~ 2 hrs 30 mins",
                "pace": "11-12/mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "April 13, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "28.4"
            }
        ]
    },
    {
        "week": "Week 20",
        "dateRange": [
            "April 14, 2025",
            "April 15, 2025",
            "April 16, 2025",
            "April 17, 2025",
            "April 18, 2025",
            "April 19, 2025",
            "April 20, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "April 14, 2025",
                "trainingPhase": "Speed & Strength",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "April 15, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "April 16, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "April 17, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 4.5",
                "duration": "40 mins",
                "pace": "~ 8:50 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "April 18, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "April 19, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "10",
                "duration": "~ 2 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "April 20, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "25.5"
            }
        ]
    },
    {
        "week": "Week 21",
        "dateRange": [
            "April 21, 2025",
            "April 22, 2025",
            "April 23, 2025",
            "April 24, 2025",
            "April 25, 2025",
            "April 26, 2025",
            "April 27, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "April 21, 2025",
                "trainingPhase": "Speed & Strength",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "April 22, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue or Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "April 23, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "April 24, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~ 4.5",
                "duration": "40 mins",
                "pace": "~ 8:50 / mi",
                "hrZone": "Mid to high orange",
                "notes": "Challenging pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "April 25, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green & Orange",
                "notes": "Speed/incline intervals",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "April 26, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "14",
                "duration": "~ 2 hrs 40 mins",
                "pace": "11-12/mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "April 27, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "29.5"
            }
        ]
    },
    {
        "week": "Week 22",
        "dateRange": [
            "April 28, 2025",
            "April 29, 2025",
            "April 30, 2025",
            "May 01, 2025",
            "May 02, 2025",
            "May 03, 2025",
            "May 04, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "April 28, 2025",
                "trainingPhase": "Taper",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green, some orange length",
                "notes": "Lighter effort",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "April 29, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "3.5",
                "duration": "30-40 mins",
                "pace": "11-12 / mi",
                "hrZone": "Ideally blue",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "April 30, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green, some orange length",
                "notes": "Lighter effort",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "May 01, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~2.75",
                "duration": "20-30 mins",
                "pace": "~ 9:00 / mi",
                "hrZone": "Mid Orange",
                "notes": "Challenging, but not overdoing it",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "May 02, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "May 03, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "8",
                "duration": "~ 1.5 hrs",
                "pace": "11-12 /mi",
                "hrZone": "Blue",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "May 04, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "19.25"
            }
        ]
    },
    {
        "week": "Week 23",
        "dateRange": [
            "May 05, 2025",
            "May 06, 2025",
            "May 07, 2025",
            "May 08, 2025",
            "May 09, 2025",
            "May 10, 2025",
            "May 11, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "May 05, 2025",
                "trainingPhase": "Taper",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green, very short orange length",
                "notes": "Very light effort",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "May 06, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "~2.5",
                "duration": "25-35 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue/Green",
                "notes": "Shakeout run",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "May 07, 2025",
                "trainingPhase": "",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Green, very short orange length",
                "notes": "Very light effort",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "May 08, 2025",
                "trainingPhase": "",
                "workoutType": "Tempo Run",
                "miles": "~2",
                "duration": "15-20 mins",
                "pace": "~ 9:00 / mi",
                "hrZone": "Mid Orange",
                "notes": "Low orange zone",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "May 09, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "May 10, 2025",
                "trainingPhase": "",
                "workoutType": "Long Run",
                "miles": "6",
                "duration": "~ 1hr 10 mins",
                "pace": "11-12 /mi",
                "hrZone": "Blue -> Green",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "May 11, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": "15.5"
            }
        ]
    },
    {
        "week": "Week 24",
        "dateRange": [
            "May 12, 2025",
            "May 13, 2025",
            "May 14, 2025",
            "May 15, 2025",
            "May 16, 2025",
            "May 17, 2025",
            "May 18, 2025"
        ],
        "activities": [
            {
                "day": "Mon",
                "date": "May 12, 2025",
                "trainingPhase": "Taper - Race Week!",
                "workoutType": "OTF",
                "miles": "~2.5",
                "duration": "",
                "pace": "",
                "hrZone": "Blue and green only",
                "notes": "Extreme light effort",
                "totalMileage": ""
            },
            {
                "day": "Tue",
                "date": "May 13, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "~2.2",
                "duration": "20-30 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Wed",
                "date": "May 14, 2025",
                "trainingPhase": "",
                "workoutType": "Walk",
                "miles": "",
                "duration": "20 mins",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Thu",
                "date": "May 15, 2025",
                "trainingPhase": "",
                "workoutType": "Easy Run",
                "miles": "~1.5",
                "duration": "15-20 mins",
                "pace": "11-12 / mi",
                "hrZone": "Blue",
                "notes": "Easy pace",
                "totalMileage": ""
            },
            {
                "day": "Fri",
                "date": "May 16, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Sat",
                "date": "May 17, 2025",
                "trainingPhase": "",
                "workoutType": "Rest",
                "miles": "",
                "duration": "",
                "pace": "",
                "hrZone": "",
                "notes": "",
                "totalMileage": ""
            },
            {
                "day": "Sun",
                "date": "May 18, 2025",
                "trainingPhase": "",
                "workoutType": "RACE",
                "miles": "13.1",
                "duration": "2 HOURS!",
                "pace": "9:09 / mi",
                "hrZone": "probs very high!",
                "notes": "",
                "totalMileage": "19.3"
            }
        ]
    }
];

let currentWeekIndex = 0; // Start with the first week

function displayCurrentWeek() {
    const container = document.querySelector('#weekContent');
    container.innerHTML = ''; // Clear previous content

    const week = trainingPlan[currentWeekIndex];

    // Create and append the week title
    const weekTitle = document.createElement('h2');
    weekTitle.textContent = week.week;
    container.appendChild(weekTitle);

    // Create and append the date range
    const startDate = week.dateRange[0];
    const endDate = week.dateRange[week.dateRange.length - 1];
    const dateRange = document.createElement('p');
    dateRange.textContent = `${startDate} - ${endDate}`;
    container.appendChild(dateRange);

    // Extract the training phase from the first activity of the week
    const firstActivity = week.activities[0];
    if (firstActivity && firstActivity.trainingPhase) {
        const trainingPhase = document.createElement('p');
        trainingPhase.textContent = `Training Phase: ${firstActivity.trainingPhase}`;
        trainingPhase.style.fontWeight = 'bold'; // Optional styling to emphasize it
        container.appendChild(trainingPhase);
    }

    // Mapping of day abbreviations to full names
    const dayMapping = {
        Mon: 'Monday',
        Tue: 'Tuesday',
        Wed: 'Wednesday',
        Thu: 'Thursday',
        Fri: 'Friday',
        Sat: 'Saturday',
        Sun: 'Sunday'
    };

    // Create a list for the activities
    const activityList = document.createElement('ul');

    // Variable to store total mileage
    let totalMileageValue = null;

    // Loop through each activity and create a structured list item
    week.activities.forEach((activity, index) => {
        const listItem = document.createElement('li');
        const activityContent = document.createElement('div');

        // Apply color based on workout type
        let borderColor = '#ccc'; // Default border color
        if (activity.workoutType === 'OTF') borderColor = '#FF9933'; // Orange for OTF
        if (activity.workoutType === 'Easy Run') borderColor = '#28A745'; // Green for Easy Run
        if (activity.workoutType === 'Long Run') borderColor = '#007BFF'; // Blue for Long Run
        if (activity.workoutType === 'Rest') borderColor = '#6C757D'; // Grey for Rest
        if (activity.workoutType === 'Tempo Run') borderColor = '#f7ea01';
 
        // Apply the border color to the list item
        listItem.style.borderLeft = `5px solid ${borderColor}`;
        listItem.style.paddingLeft = '10px'; // Add padding to separate the text from the border

        // Create a strong element for the day with the full name
        const dayElement = document.createElement('strong');
        dayElement.textContent = `${dayMapping[activity.day] || activity.day} `;
        activityContent.appendChild(dayElement);

        // Skip adding the training phase again in the list
        if (index !== 0 && activity.trainingPhase) {
            // Skip adding training phase for subsequent activities
        }

        // Add each piece of workout information as a separate paragraph with subtle labels
        if (activity.workoutType) {
            const workoutType = document.createElement('p');
            workoutType.innerHTML = `<span class="label">Workout Type:</span> ${activity.workoutType}`;
            activityContent.appendChild(workoutType);
        }

        if (activity.miles) {
            const miles = document.createElement('p');
            miles.innerHTML = `<span class="label">Miles:</span> ${activity.miles}`;
            activityContent.appendChild(miles);
        }

        if (activity.duration) {
            const duration = document.createElement('p');
            duration.innerHTML = `<span class="label">Duration:</span> ${activity.duration}`;
            activityContent.appendChild(duration);
        }

        if (activity.pace) {
            const pace = document.createElement('p');
            pace.innerHTML = `<span class="label">Pace:</span> ${activity.pace}`;
            activityContent.appendChild(pace);
        }

        if (activity.hrZone) {
            const hrZone = document.createElement('p');
            hrZone.innerHTML = `<span class="label">HR Zone:</span> ${activity.hrZone}`;
            activityContent.appendChild(hrZone);
        }

        if (activity.notes) {
            const notes = document.createElement('p');
            notes.innerHTML = `<span class="label">Notes:</span> ${activity.notes}`;
            activityContent.appendChild(notes);
        }

        // Check if this is Sunday's activity and has totalMileage
        if (activity.day === 'Sun' && activity.totalMileage) {
            totalMileageValue = activity.totalMileage;
        }

        // Append the structured content to the list item
        listItem.appendChild(activityContent);
        activityList.appendChild(listItem);
    });

    // Append the activity list to the container
    container.appendChild(activityList);

    // Create and append the total mileage if it exists
    if (totalMileageValue) {
        const totalMileage = document.createElement('h3');
        totalMileage.textContent = `Total Mileage: ${totalMileageValue}`;
        container.appendChild(totalMileage);
    }
}



// Function to parse date strings into Date objects
function parseDate(dateStr) {
    return new Date(Date.parse(dateStr));
}

// Function to find the current week based on today's date
function findCurrentWeek() {
    const today = new Date();
    
    for (let i = 0; i < trainingPlan.length; i++) {
        const startDate = parseDate(trainingPlan[i].dateRange[0]);
        const endDate = parseDate(trainingPlan[i].dateRange[1]);

        if (today >= startDate && today <= endDate) {
            return i; // Return the index of the current week
        }
    }
    
    // If today's date is before the first week's start date, return 0
    return 0;
}

// Function to handle navigation
function navigateWeek(direction) {
    currentWeekIndex += direction;

    // Ensure the index stays within bounds
    if (currentWeekIndex < 0) currentWeekIndex = 0;
    if (currentWeekIndex >= trainingPlan.length) currentWeekIndex = trainingPlan.length - 1;

    // Update the dropdown value and display the current week
    document.getElementById('weekDropdown').value = currentWeekIndex;
    displayCurrentWeek();
}

function createWeekDropdown() {
    const weekDropdown = document.getElementById('weekDropdown');

    trainingPlan.forEach((week, index) => {
        const startDate = week.dateRange[0];
        const option = document.createElement('option');
        option.value = index;

        // Show only "Week 3" as the main text
        option.textContent = `Week ${index + 1}`;

        // Use the full details as the title attribute, which will be visible in the dropdown
        option.title = `${week.week}: ${startDate} - ${week.dateRange[week.dateRange.length - 1]}`;

        // When the dropdown is expanded, the browser will show the full details
        weekDropdown.appendChild(option);
    });

    // Set the dropdown to the current week on page load
    weekDropdown.value = currentWeekIndex;

    // Event listener for week selection
    weekDropdown.addEventListener('change', (event) => {
        currentWeekIndex = parseInt(event.target.value);
        displayCurrentWeek();
    });
}

// Add event listeners for navigation buttons
document.getElementById('prevWeek').addEventListener('click', () => navigateWeek(-1));
document.getElementById('nextWeek').addEventListener('click', () => navigateWeek(1));


// Determine the initial current week
currentWeekIndex = findCurrentWeek();


// Display the first week on page load
// Initialize the week tabs and display the current week
window.onload = createWeekDropdown();
window.onload = displayCurrentWeek();
